### ISSUE TITLE
xd[] is weird..why is it not initiated as a vector?

### ISSUE THREAD

**Issue by hy565** [mrsd16teamd/loco_car#1]
xd[] is weird..why is it not initiated as a vector? and why xd+6 and not xd+5? @kazuotani14

**Comment by kazuotani14** [comment]
The way it was implemented is the easiest way I know to initialize std::vector with hardcoded values. See here: http://stackoverflow.com/questions/2236197/what-is-the-easiest-way-to-initialize-a-stdvector-with-hardcoded-elements 

I think it should be xd+6 because it's basically providing pointers to the 'start' and 'end' of the array, via pointer arithmetic. xd+5 would be a pointer to the beginning of the 6th element, so the last 0 wouldn't be included. No idea why the code works without that last 0.

**Comment by aumj** [comment]
Apparently C++11 is not default. Got build errors when I tried initialization lists. Reverting to the original approach.
